#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
#  LoAuth Installer — macOS / Linux
#  Usage:
#    bash install.sh            Install LoAuth + register global command
#    bash install.sh --uninstall Remove the global command and .venv
# ──────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────
CYAN='\033[96m'
GREEN='\033[92m'
YELLOW='\033[93m'
RED='\033[91m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
BIN_NAME="loauth"

print_banner() {
    echo -e "${CYAN}${BOLD}"
    echo "  ██╗      ██████╗  █████╗ ██╗   ██╗████████╗██╗  ██╗"
    echo "  ██║     ██╔═══██╗██╔══██╗██║   ██║╚══██╔══╝██║  ██║"
    echo "  ██║     ██║   ██║███████║██║   ██║   ██║   ███████║"
    echo "  ██║     ██║   ██║██╔══██║██║   ██║   ██║   ██╔══██║"
    echo "  ███████╗╚██████╔╝██║  ██║╚██████╔╝   ██║   ██║  ██║"
    echo "  ╚══════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝"
    echo -e "${RESET}"
    echo -e "${CYAN}  Secure 2FA Authenticator${RESET}"
    echo ""
}

# ── Uninstall mode ────────────────────────────────────────────────────────
if [[ "${1:-}" == "--uninstall" ]]; then
    print_banner
    echo -e "${YELLOW}[…]${RESET} Uninstalling LoAuth…"

    # Remove global command
    for dir in "$HOME/.local/bin" "/usr/local/bin"; do
        if [ -f "$dir/$BIN_NAME" ]; then
            rm -f "$dir/$BIN_NAME"
            echo -e "${GREEN}[✓]${RESET} Removed $dir/$BIN_NAME"
        fi
    done

    # Remove virtual environment
    if [ -d "$VENV_DIR" ]; then
        rm -rf "$VENV_DIR"
        echo -e "${GREEN}[✓]${RESET} Removed .venv/"
    fi

    echo ""
    echo -e "${GREEN}${BOLD}  ✅  Uninstall complete.${RESET}"
    echo -e "${DIM}  Project files remain in: $PROJECT_DIR${RESET}"
    echo -e "${DIM}  Your vault (data/vault.db) was NOT deleted.${RESET}"
    echo ""
    exit 0
fi

# ── Install mode ──────────────────────────────────────────────────────────
print_banner

# ── 1. Check Python ──────────────────────────────────────────────────────
PYTHON=""
for cmd in python3 python; do
    if command -v "$cmd" &>/dev/null; then
        ver=$("$cmd" -c 'import sys; print(sys.version_info.major)' 2>/dev/null || echo "0")
        if [ "$ver" = "3" ]; then
            PYTHON="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON" ]; then
    echo -e "${RED}[✗] Python 3 is not installed.${RESET}"
    echo "    Install it from https://www.python.org/downloads/"
    exit 1
fi

PY_VERSION=$("$PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo -e "${GREEN}[✓]${RESET} Python ${PY_VERSION} detected  →  $("$PYTHON" --version 2>&1)"

# ── 2. Create virtual environment ────────────────────────────────────────
if [ ! -d "$VENV_DIR" ]; then
    echo -e "${YELLOW}[…]${RESET} Creating virtual environment…"
    "$PYTHON" -m venv "$VENV_DIR"
fi
echo -e "${GREEN}[✓]${RESET} Virtual environment ready  →  .venv/"

# Activate
source "$VENV_DIR/bin/activate"

# ── 3. Install dependencies ──────────────────────────────────────────────
echo -e "${YELLOW}[…]${RESET} Installing dependencies…"
pip install --upgrade pip --quiet 2>&1 | tail -1 || true
pip install -r "$PROJECT_DIR/requirements.txt" --quiet
echo -e "${GREEN}[✓]${RESET} Dependencies installed  →  flet, pyotp, cryptography, argon2-cffi"

# ── 4. Register global command ───────────────────────────────────────────
TARGET_DIR=""
if [ -d "$HOME/.local/bin" ] || mkdir -p "$HOME/.local/bin" 2>/dev/null; then
    TARGET_DIR="$HOME/.local/bin"
elif [ -d "/usr/local/bin" ] && [ -w "/usr/local/bin" ]; then
    TARGET_DIR="/usr/local/bin"
fi

if [ -z "$TARGET_DIR" ]; then
    echo -e "${YELLOW}[!]${RESET} Could not find a writable bin directory."
    echo "    Run manually:  source .venv/bin/activate && python main.py"
else
    LAUNCHER="$TARGET_DIR/$BIN_NAME"

    cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by LoAuth installer
source "$VENV_DIR/bin/activate"
exec "$VENV_DIR/bin/python" "$PROJECT_DIR/main.py" "\$@"
EOF

    chmod +x "$LAUNCHER"
    echo -e "${GREEN}[✓]${RESET} Global command registered  →  ${BOLD}${BIN_NAME}${RESET}"

    # Check if TARGET_DIR is in PATH
    if ! echo "$PATH" | tr ':' '\n' | grep -qx "$TARGET_DIR"; then
        echo ""
        echo -e "${YELLOW}[!]${RESET} ${BOLD}$TARGET_DIR${RESET} is not in your PATH."
        echo "    Add this to your shell profile (~/.zshrc or ~/.bashrc):"
        echo ""
        echo -e "    ${CYAN}export PATH=\"\$HOME/.local/bin:\$PATH\"${RESET}"
        echo ""
    fi
fi

# ── Done ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  ✅  Installation complete!${RESET}"
echo ""
echo -e "  ${BOLD}Launch GUI:${RESET}   ${CYAN}loauth${RESET}"
echo -e "  ${BOLD}Launch CLI:${RESET}   ${CYAN}loauth --cli${RESET}"
echo -e "  ${BOLD}Uninstall:${RESET}    ${CYAN}bash install.sh --uninstall${RESET}"
echo ""
